### ISSUE TITLE
RNN not wroking properly 

### ISSUE THREAD

**Issue by zain581** [kernel-loophole/Natrual-Language-Process#7]
model = Sequential()
model.add(Embedding(10000, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))

model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.summary()

**Comment by kernel-loophole** [comment]
# try this 
model = Sequential()
model.add(Embedding(10000, 64))
model.add(SimpleRNN(64, return_sequences=True))
model.add(SimpleRNN(64, return_sequences=True))

model.add(SimpleRNN(64, return_sequences=True))
model.add(SimpleRNN(64))
model.summary()

**Comment by zain581** [comment]
let me check it

**Comment by zain581** [comment]
great
