### ISSUE TITLE
this again not working

### ISSUE THREAD

**Issue by zain581** [kernel-loophole/Natrual-Language-Process#8]
model = Sequential()
model.add(Embedding(10000, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))

model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.summary()

**Comment by kernel-loophole** [comment]
#TRY  with 128 layers  

model = Sequential()
model.add(Embedding(10000, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))

model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.summary()

**Comment by zain581** [comment]
worked
